//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpulseApp.StubService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/StubMethods")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StubService.IStubService")]
    public interface IStubService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStubService/GenerateStats", ReplyAction="http://tempuri.org/IStubService/GenerateStatsResponse")]
        string GenerateStats(int AdID, string beginDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStubService/GenerateStats", ReplyAction="http://tempuri.org/IStubService/GenerateStatsResponse")]
        System.Threading.Tasks.Task<string> GenerateStatsAsync(int AdID, string beginDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStubService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IStubService/GetDataUsingDataContractResponse")]
        ImpulseApp.StubService.CompositeType GetDataUsingDataContract(ImpulseApp.StubService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStubService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IStubService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ImpulseApp.StubService.CompositeType> GetDataUsingDataContractAsync(ImpulseApp.StubService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStubServiceChannel : ImpulseApp.StubService.IStubService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StubServiceClient : System.ServiceModel.ClientBase<ImpulseApp.StubService.IStubService>, ImpulseApp.StubService.IStubService {
        
        public StubServiceClient() {
        }
        
        public StubServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StubServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StubServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StubServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GenerateStats(int AdID, string beginDate, string endDate) {
            return base.Channel.GenerateStats(AdID, beginDate, endDate);
        }
        
        public System.Threading.Tasks.Task<string> GenerateStatsAsync(int AdID, string beginDate, string endDate) {
            return base.Channel.GenerateStatsAsync(AdID, beginDate, endDate);
        }
        
        public ImpulseApp.StubService.CompositeType GetDataUsingDataContract(ImpulseApp.StubService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ImpulseApp.StubService.CompositeType> GetDataUsingDataContractAsync(ImpulseApp.StubService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
