//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpulseApp.Outbound.DBService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleAdModel", Namespace="http://schemas.datacontract.org/2004/07/ImpulseApp.Models.AdModels")]
    [System.SerializableAttribute()]
    public partial class SimpleAdModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImpulseApp.Outbound.DBService.AdSession[] AdSessionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HtmlSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortUrlKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImpulseApp.Outbound.DBService.AdSession[] AdSessions {
            get {
                return this.AdSessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdSessionsField, value) != true)) {
                    this.AdSessionsField = value;
                    this.RaisePropertyChanged("AdSessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HtmlSource {
            get {
                return this.HtmlSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.HtmlSourceField, value) != true)) {
                    this.HtmlSourceField = value;
                    this.RaisePropertyChanged("HtmlSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortUrlKey {
            get {
                return this.ShortUrlKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortUrlKeyField, value) != true)) {
                    this.ShortUrlKeyField = value;
                    this.RaisePropertyChanged("ShortUrlKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdSession", Namespace="http://schemas.datacontract.org/2004/07/ImpulseApp.Models.StatModels")]
    [System.SerializableAttribute()]
    public partial class AdSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveMillisecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImpulseApp.Outbound.DBService.Activity[] ActivitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImpulseApp.Outbound.DBService.SimpleAdModel AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserBrowserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLocaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveMilliseconds {
            get {
                return this.ActiveMillisecondsField;
            }
            set {
                if ((this.ActiveMillisecondsField.Equals(value) != true)) {
                    this.ActiveMillisecondsField = value;
                    this.RaisePropertyChanged("ActiveMilliseconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImpulseApp.Outbound.DBService.Activity[] Activities {
            get {
                return this.ActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivitiesField, value) != true)) {
                    this.ActivitiesField = value;
                    this.RaisePropertyChanged("Activities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImpulseApp.Outbound.DBService.SimpleAdModel Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdId {
            get {
                return this.AdIdField;
            }
            set {
                if ((this.AdIdField.Equals(value) != true)) {
                    this.AdIdField = value;
                    this.RaisePropertyChanged("AdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeEnd {
            get {
                return this.DateTimeEndField;
            }
            set {
                if ((this.DateTimeEndField.Equals(value) != true)) {
                    this.DateTimeEndField = value;
                    this.RaisePropertyChanged("DateTimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeStart {
            get {
                return this.DateTimeStartField;
            }
            set {
                if ((this.DateTimeStartField.Equals(value) != true)) {
                    this.DateTimeStartField = value;
                    this.RaisePropertyChanged("DateTimeStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserBrowser {
            get {
                return this.UserBrowserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserBrowserField, value) != true)) {
                    this.UserBrowserField = value;
                    this.RaisePropertyChanged("UserBrowser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserIp {
            get {
                return this.UserIpField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIpField, value) != true)) {
                    this.UserIpField = value;
                    this.RaisePropertyChanged("UserIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLocale {
            get {
                return this.UserLocaleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLocaleField, value) != true)) {
                    this.UserLocaleField = value;
                    this.RaisePropertyChanged("UserLocale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLocation {
            get {
                return this.UserLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLocationField, value) != true)) {
                    this.UserLocationField = value;
                    this.RaisePropertyChanged("UserLocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Activity", Namespace="http://schemas.datacontract.org/2004/07/ImpulseApp.Models.StatModels")]
    [System.SerializableAttribute()]
    public partial class Activity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImpulseApp.Outbound.DBService.Click[] ClicksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImpulseApp.Outbound.DBService.AdSession SessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImpulseApp.Outbound.DBService.Click[] Clicks {
            get {
                return this.ClicksField;
            }
            set {
                if ((object.ReferenceEquals(this.ClicksField, value) != true)) {
                    this.ClicksField = value;
                    this.RaisePropertyChanged("Clicks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImpulseApp.Outbound.DBService.AdSession Session {
            get {
                return this.SessionField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionField, value) != true)) {
                    this.SessionField = value;
                    this.RaisePropertyChanged("Session");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Click", Namespace="http://schemas.datacontract.org/2004/07/ImpulseApp.Models.StatModels")]
    [System.SerializableAttribute()]
    public partial class Click : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ImpulseApp.Outbound.DBService.Activity ActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActivityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClickIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClickTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClickTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClickZoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ImpulseApp.Outbound.DBService.Activity Activity {
            get {
                return this.ActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityField, value) != true)) {
                    this.ActivityField = value;
                    this.RaisePropertyChanged("Activity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActivityId {
            get {
                return this.ActivityIdField;
            }
            set {
                if ((this.ActivityIdField.Equals(value) != true)) {
                    this.ActivityIdField = value;
                    this.RaisePropertyChanged("ActivityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClickId {
            get {
                return this.ClickIdField;
            }
            set {
                if ((this.ClickIdField.Equals(value) != true)) {
                    this.ClickIdField = value;
                    this.RaisePropertyChanged("ClickId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ClickTime {
            get {
                return this.ClickTimeField;
            }
            set {
                if ((this.ClickTimeField.Equals(value) != true)) {
                    this.ClickTimeField = value;
                    this.RaisePropertyChanged("ClickTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClickType {
            get {
                return this.ClickTypeField;
            }
            set {
                if ((this.ClickTypeField.Equals(value) != true)) {
                    this.ClickTypeField = value;
                    this.RaisePropertyChanged("ClickType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClickZone {
            get {
                return this.ClickZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ClickZoneField, value) != true)) {
                    this.ClickZoneField = value;
                    this.RaisePropertyChanged("ClickZone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBService.IDBService")]
    public interface IDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetUserAds", ReplyAction="http://tempuri.org/IDBService/GetUserAdsResponse")]
        ImpulseApp.Outbound.DBService.SimpleAdModel[] GetUserAds(string UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetUserAds", ReplyAction="http://tempuri.org/IDBService/GetUserAdsResponse")]
        System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.SimpleAdModel[]> GetUserAdsAsync(string UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetAdByUrl", ReplyAction="http://tempuri.org/IDBService/GetAdByUrlResponse")]
        ImpulseApp.Outbound.DBService.SimpleAdModel GetAdByUrl(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetAdByUrl", ReplyAction="http://tempuri.org/IDBService/GetAdByUrlResponse")]
        System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.SimpleAdModel> GetAdByUrlAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetAdById", ReplyAction="http://tempuri.org/IDBService/GetAdByIdResponse")]
        ImpulseApp.Outbound.DBService.SimpleAdModel GetAdById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetAdById", ReplyAction="http://tempuri.org/IDBService/GetAdByIdResponse")]
        System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.SimpleAdModel> GetAdByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SaveAd", ReplyAction="http://tempuri.org/IDBService/SaveAdResponse")]
        string SaveAd(ImpulseApp.Outbound.DBService.SimpleAdModel model, bool proceedToDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SaveAd", ReplyAction="http://tempuri.org/IDBService/SaveAdResponse")]
        System.Threading.Tasks.Task<string> SaveAdAsync(ImpulseApp.Outbound.DBService.SimpleAdModel model, bool proceedToDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetSessionsByAdId", ReplyAction="http://tempuri.org/IDBService/GetSessionsByAdIdResponse")]
        ImpulseApp.Outbound.DBService.AdSession[] GetSessionsByAdId(int AdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetSessionsByAdId", ReplyAction="http://tempuri.org/IDBService/GetSessionsByAdIdResponse")]
        System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.AdSession[]> GetSessionsByAdIdAsync(int AdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SaveAdSession", ReplyAction="http://tempuri.org/IDBService/SaveAdSessionResponse")]
        string SaveAdSession(ImpulseApp.Outbound.DBService.AdSession model, bool proceedToDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SaveAdSession", ReplyAction="http://tempuri.org/IDBService/SaveAdSessionResponse")]
        System.Threading.Tasks.Task<string> SaveAdSessionAsync(ImpulseApp.Outbound.DBService.AdSession model, bool proceedToDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetActivityBySessionId", ReplyAction="http://tempuri.org/IDBService/GetActivityBySessionIdResponse")]
        ImpulseApp.Outbound.DBService.Activity[] GetActivityBySessionId(int SessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetActivityBySessionId", ReplyAction="http://tempuri.org/IDBService/GetActivityBySessionIdResponse")]
        System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.Activity[]> GetActivityBySessionIdAsync(int SessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SaveActivity", ReplyAction="http://tempuri.org/IDBService/SaveActivityResponse")]
        string SaveActivity(ImpulseApp.Outbound.DBService.Activity model, bool proceedToDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SaveActivity", ReplyAction="http://tempuri.org/IDBService/SaveActivityResponse")]
        System.Threading.Tasks.Task<string> SaveActivityAsync(ImpulseApp.Outbound.DBService.Activity model, bool proceedToDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetClicksByActivityId", ReplyAction="http://tempuri.org/IDBService/GetClicksByActivityIdResponse")]
        ImpulseApp.Outbound.DBService.Click[] GetClicksByActivityId(int ActivityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetClicksByActivityId", ReplyAction="http://tempuri.org/IDBService/GetClicksByActivityIdResponse")]
        System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.Click[]> GetClicksByActivityIdAsync(int ActivityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SaveClick", ReplyAction="http://tempuri.org/IDBService/SaveClickResponse")]
        string SaveClick(ImpulseApp.Outbound.DBService.Click model, bool proceedToDB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/SaveClick", ReplyAction="http://tempuri.org/IDBService/SaveClickResponse")]
        System.Threading.Tasks.Task<string> SaveClickAsync(ImpulseApp.Outbound.DBService.Click model, bool proceedToDB);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBServiceChannel : ImpulseApp.Outbound.DBService.IDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<ImpulseApp.Outbound.DBService.IDBService>, ImpulseApp.Outbound.DBService.IDBService {
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ImpulseApp.Outbound.DBService.SimpleAdModel[] GetUserAds(string UserId) {
            return base.Channel.GetUserAds(UserId);
        }
        
        public System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.SimpleAdModel[]> GetUserAdsAsync(string UserId) {
            return base.Channel.GetUserAdsAsync(UserId);
        }
        
        public ImpulseApp.Outbound.DBService.SimpleAdModel GetAdByUrl(string url) {
            return base.Channel.GetAdByUrl(url);
        }
        
        public System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.SimpleAdModel> GetAdByUrlAsync(string url) {
            return base.Channel.GetAdByUrlAsync(url);
        }
        
        public ImpulseApp.Outbound.DBService.SimpleAdModel GetAdById(int id) {
            return base.Channel.GetAdById(id);
        }
        
        public System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.SimpleAdModel> GetAdByIdAsync(int id) {
            return base.Channel.GetAdByIdAsync(id);
        }
        
        public string SaveAd(ImpulseApp.Outbound.DBService.SimpleAdModel model, bool proceedToDB) {
            return base.Channel.SaveAd(model, proceedToDB);
        }
        
        public System.Threading.Tasks.Task<string> SaveAdAsync(ImpulseApp.Outbound.DBService.SimpleAdModel model, bool proceedToDB) {
            return base.Channel.SaveAdAsync(model, proceedToDB);
        }
        
        public ImpulseApp.Outbound.DBService.AdSession[] GetSessionsByAdId(int AdId) {
            return base.Channel.GetSessionsByAdId(AdId);
        }
        
        public System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.AdSession[]> GetSessionsByAdIdAsync(int AdId) {
            return base.Channel.GetSessionsByAdIdAsync(AdId);
        }
        
        public string SaveAdSession(ImpulseApp.Outbound.DBService.AdSession model, bool proceedToDB) {
            return base.Channel.SaveAdSession(model, proceedToDB);
        }
        
        public System.Threading.Tasks.Task<string> SaveAdSessionAsync(ImpulseApp.Outbound.DBService.AdSession model, bool proceedToDB) {
            return base.Channel.SaveAdSessionAsync(model, proceedToDB);
        }
        
        public ImpulseApp.Outbound.DBService.Activity[] GetActivityBySessionId(int SessionId) {
            return base.Channel.GetActivityBySessionId(SessionId);
        }
        
        public System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.Activity[]> GetActivityBySessionIdAsync(int SessionId) {
            return base.Channel.GetActivityBySessionIdAsync(SessionId);
        }
        
        public string SaveActivity(ImpulseApp.Outbound.DBService.Activity model, bool proceedToDB) {
            return base.Channel.SaveActivity(model, proceedToDB);
        }
        
        public System.Threading.Tasks.Task<string> SaveActivityAsync(ImpulseApp.Outbound.DBService.Activity model, bool proceedToDB) {
            return base.Channel.SaveActivityAsync(model, proceedToDB);
        }
        
        public ImpulseApp.Outbound.DBService.Click[] GetClicksByActivityId(int ActivityId) {
            return base.Channel.GetClicksByActivityId(ActivityId);
        }
        
        public System.Threading.Tasks.Task<ImpulseApp.Outbound.DBService.Click[]> GetClicksByActivityIdAsync(int ActivityId) {
            return base.Channel.GetClicksByActivityIdAsync(ActivityId);
        }
        
        public string SaveClick(ImpulseApp.Outbound.DBService.Click model, bool proceedToDB) {
            return base.Channel.SaveClick(model, proceedToDB);
        }
        
        public System.Threading.Tasks.Task<string> SaveClickAsync(ImpulseApp.Outbound.DBService.Click model, bool proceedToDB) {
            return base.Channel.SaveClickAsync(model, proceedToDB);
        }
    }
}
