// <auto-generated />
namespace ImpulseApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class migr_stats2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migr_stats2));
        
        string IMigrationMetadata.Id
        {
            get { return "201411061423163_migr_stats2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
