// <auto-generated />
namespace ImpulseApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_AdModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_AdModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201409210922504_add_AdModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
